In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('orders.csv')

In [3]:
df

     order_id customer_id product_id  quantity   amount currency  order_date
0      O00545       C0115      P0011         3    33.78      INR  2026-04-28
1      O00071       C0048      P0037         4   399.24      EUR  2026-03-21
2     O00550        C0103      P0059         4   494.92      EUR  2026-03-16
3      O00528       C0081      P0018         2   286.14      USD  2026-02-04
4      O00456       C0034      P0040         3   352.80      INR  20/04/2026
..        ...         ...        ...       ...      ...      ...         ...
913    O00813       C0113      P0053         4  1555.88      EUR  02-01-2026
914    O00360       C0037      P0051         5   235.80      INR  02-21-2026
915    O00128       C0082      P0019         3  1129.47      EUR  2026-06-30
916    O00481       C0069      P0040         5   588.00      INR  07/02/2026
917    O00877       C0090      P0022         4  1599.72      INR  2026-04-11

[918 rows x 7 columns]

In [4]:
df.head() # First 5 rows

   order_id customer_id product_id  quantity  amount currency  order_date
0    O00545       C0115      P0011         3   33.78      INR  2026-04-28
1    O00071       C0048      P0037         4  399.24      EUR  2026-03-21
2   O00550        C0103      P0059         4  494.92      EUR  2026-03-16
3    O00528       C0081      P0018         2  286.14      USD  2026-02-04
4    O00456       C0034      P0040         3  352.80      INR  20/04/2026

In [5]:
df.tail() # Last 5 rows

    order_id customer_id product_id  quantity   amount currency  order_date
913   O00813       C0113      P0053         4  1555.88      EUR  02-01-2026
914   O00360       C0037      P0051         5   235.80      INR  02-21-2026
915   O00128       C0082      P0019         3  1129.47      EUR  2026-06-30
916   O00481       C0069      P0040         5   588.00      INR  07/02/2026
917   O00877       C0090      P0022         4  1599.72      INR  2026-04-11

In [6]:
df.info() # Column types and non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     918 non-null    object
 1   customer_id  865 non-null    object
 2   product_id   918 non-null    object
 3   quantity     918 non-null    int64
 4   amount       885 non-null    float64
 5   currency     918 non-null    object
 6   order_date   918 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 50.3+ KB

In [7]:
df.describe() # summary stats

         quantity       amount
count  918.000000   885.000000
mean     2.847495   683.066407
std      1.610573   597.479985
min     -2.000000     0.000000
25%      2.000000   215.620000
50%      3.000000   474.700000
75%      4.000000   987.400000
max      5.000000  2451.750000

In [8]:
df.columns # Column names

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'amount',
       'currency', 'order_date'],
      dtype='object')

In [9]:
df.index # Row indices

RangeIndex(start=0, stop=918, step=1)

In [10]:
# df['currency'] # returns value of particular column
# len(df['currency']) # returns length
set(df['currency']) # returns set

{'EUR', 'GBP', 'INR', 'USD'}

In [11]:
df[['currency','amount']] # returns multiple column

    currency   amount
0        INR    33.78
1        EUR   399.24
2        EUR   494.92
3        USD   286.14
4        INR   352.80
..       ...      ...
913      EUR  1555.88
914      INR   235.80
915      EUR  1129.47
916      INR   588.00
917      INR  1599.72

[918 rows x 2 columns]

In [12]:
df.iloc[1]

order_id           O00071
customer_id         C0048
product_id          P0037
quantity                4
amount             399.24
currency              EUR
order_date     2026-03-21
Name: 1, dtype: object

In [13]:
df.loc[1]

order_id           O00071
customer_id         C0048
product_id          P0037
quantity                4
amount             399.24
currency              EUR
order_date     2026-03-21
Name: 1, dtype: object

In [14]:
df.columns

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'amount',
       'currency', 'order_date'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     918 non-null    object
 1   customer_id  865 non-null    object
 2   product_id   918 non-null    object
 3   quantity     918 non-null    int64
 4   amount       885 non-null    float64
 5   currency     918 non-null    object
 6   order_date   918 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 50.3+ KB

In [16]:
df[(df['order_date']=='2026-03-24') & (df['product_id']=='P0049')]

   order_id customer_id product_id  quantity  amount currency  order_date
26   O00683       C0007      P0049         5  208.35      GBP  2026-03-24

In [17]:
df[(df['order_date']=='2026-03-24') | (df['product_id']=='P0049')]

     order_id customer_id product_id  quantity   amount currency  order_date
26     O00683       C0007      P0049         5   208.35      GBP  2026-03-24
54     O00574       C0030      P0049         3   125.01      GBP  04-08-2026
86     O00311       C0008      P0049         2    83.34      GBP  04-08-2026
89     O00755         NaN      P0049         1    41.67      GBP  2026-05-09
98     O00585       C0092      P0049         1    41.67      GBP  06/05/2026
124    O00297       C0112      P0049         4   166.68      GBP  10/05/2026
127    O00814       C0022      P0049         4   166.68      GBP  2026-03-11
172    O00727       C0018      P0049         5   208.35      INR  03-12-2026
210    O00579       C0093      P0049         5   208.35      GBP  14/04/2026
216    O00129       C0071      P0049         5   208.35      GBP  06-05-2026
247   O00705        C0052      P0049         4   166.68      GBP  24/05/2026
284    O00419       C0051      P0049         5   208.35      GBP  02-09-2026
290    O00750       C0080      P0035         4  1448.16      USD  2026-03-24
389    O00052       C0028      P0049         3   125.01      GBP  15/01/2026
476    O00187         NaN      P0049         2    83.34      GBP  2026-04-24
500    O00729       C0076      P0049         4   166.68      GBP  02-23-2026
503    O00699       C0064      P0049         1    41.67      GBP  01/02/2026
521    O00556       C0120      P0049         4   166.68      GBP  2026-05-02
532    O00763       C0055      P0049         3   125.01      GBP  04/05/2026
595    O00890       C0028      P0049         4   166.68      GBP  2026-04-21
767    O00503       C0017      P0049         5   208.35      GBP  01-31-2026
777    O00290       C0015      P0049         0     0.00      GBP  06-23-2026
832    O00331       C0110      P0049         5   208.35      GBP  01-30-2026
839    O00297       C0112      P0049         4   166.68      GBP  10/05/2026
840    O00591       C0064      P0049         3   125.01      GBP  26/06/2026
897    O00675       C0107      P0049         2    83.34      GBP  04-07-2026

In [18]:
df[(df['amount'] > 1970) & (df['amount'] < 2000)]

    order_id customer_id product_id  quantity   amount currency  order_date
417   O00811       C0032      P0008         5  1995.65      USD  04-22-2026
484   O00762       C0022      P0028         5  1987.50      GBP  21/01/2026
785   O00594       C0065      P0028         5  1987.50      GBP  20/01/2026
807   O00797       C0023      P0008         5  1995.65      USD  15/01/2026
843   O00517       C0087      P0008         5  1995.65      USD  04-20-2026

In [19]:
df[df['currency'].str.startswith('E')]
df[df['currency'].str.endswith('D')]

    order_id customer_id product_id  quantity   amount currency  order_date
3     O00528       C0081      P0018         2   286.14      USD  2026-02-04
6     O00003       C0118      P0008         4  1596.52      USD  03-20-2026
8     O00387       C0045      P0035         1   362.04      USD  2026-01-01
16    O00552         NaN      P0035         4  1448.16      USD  30/05/2026
17    O00772       C0001      P0050         4   320.40      USD  02/01/2026
..       ...         ...        ...       ...      ...      ...         ...
887   O00034       C0046      P0018         2   286.14      USD  04-05-2026
890   O00248       C0093      P0035         3  1086.12      USD  02-18-2026
895   O00315       C0048      P0035         5  1810.20      USD  06-12-2026
896   O00271       C0088      P0002         4  1560.04      USD  03/06/2026
910   O00841       C0058      P0008         4  1596.52      USD  06/03/2026

[188 rows x 7 columns]

In [20]:
df[df["customer_id"].isin(['COO03','C0001','C0002'])]
df[~df["customer_id"].isin(['COO03','C0001','C0002'])] # reverse the above condition

     order_id customer_id product_id  quantity   amount currency  order_date
0      O00545       C0115      P0011         3    33.78      INR  2026-04-28
1      O00071       C0048      P0037         4   399.24      EUR  2026-03-21
2     O00550        C0103      P0059         4   494.92      EUR  2026-03-16
3      O00528       C0081      P0018         2   286.14      USD  2026-02-04
4      O00456       C0034      P0040         3   352.80      INR  20/04/2026
..        ...         ...        ...       ...      ...      ...         ...
913    O00813       C0113      P0053         4  1555.88      EUR  02-01-2026
914    O00360       C0037      P0051         5   235.80      INR  02-21-2026
915    O00128       C0082      P0019         3  1129.47      EUR  2026-06-30
916    O00481       C0069      P0040         5   588.00      INR  07/02/2026
917    O00877       C0090      P0022         4  1599.72      INR  2026-04-11

[902 rows x 7 columns]

In [21]:
df.loc[df["customer_id"] == "C0015","product_id"] = "007"

In [22]:
df.loc[df["customer_id"] == "C0015"]

    order_id customer_id product_id  quantity   amount currency  order_date
81    O00589       C0015        007         5  1950.05      USD  22/01/2026
125   O00177       C0015        007         2   941.66      INR  2026-03-17
208   O00037       C0015        007         0      NaN      USD  2026-02-03
565   O00672       C0015        007         3   299.43      EUR  31/01/2026
574   O00870       C0015        007         1   474.06      USD  15/06/2026
590   O00038       C0015        007         4   957.04      INR  02-02-2026
687   O00211       C0015        007         1   490.35      INR  04/03/2026
777   O00290       C0015        007         0     0.00      GBP  06-23-2026

In [23]:
df['currency'] = df['currency'].str.upper()

In [29]:
df = df.drop(2)
df.head()

  order_id customer_id product_id  quantity  amount currency  order_date
0   O00545       C0115      P0011         3   33.78      INR  2026-04-28
1   O00071       C0048      P0037         4  399.24      EUR  2026-03-21
3   O00528       C0081      P0018         2  286.14      USD  2026-02-04
4   O00456       C0034      P0040         3  352.80      INR  20/04/2026
5   O00307       C0044      P0029         2  229.38      INR  27/06/2026